### ISSUE TITLE
epoll issues

### ISSUE THREAD

**Issue by lavolp3** [mboskamp/MMM-PIR#16]
module epoll  that is installed via onoff creates problems!
```
2019-12-17T21:22:41 <error> WARNING! Could not load config file. Starting with default configuration. Error found: Error: The module '/home/pi/MagicMirror/modules/MMM-PIR/node_modules/onoff/node_modules/epoll/build/Release/epoll.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 67. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`). (/home/pi/MagicMirror/js/app.js:74 loadConfig)
2
```
node v 11.4.0
npm v 6.13.0
MM v 2.8.0

**Comment by Einixx** [comment]
If the issue is still open for you, I found this in another forum:
from the MMM-PIR folder

npm install electron-rebuild
then run it to force the epoll rebuild

node_modules/.bin/electron-rebuild

**Comment by lavolp3** [comment]
Thanks!

**Comment by lavolp3** [comment]
I would suggest to somehow include this information in the README or wiki, otherwise it might get lost. My issue is solved.
