### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by mimaret** [mboskamp/MMM-PIR#19]
Hello,

Would it be possible to insert a French translation.
I enclose the contents of the file fr.json

{
  "HEADER": "Délai avant extinction:",
  "LAST_USER_PRESENCE": "Dernière activité:",
  "TELEGRAM_COMMAND_ERROR": "Erreur lors de l'exécution de la commande `{command}`."
}

I thank you in advance.

**Comment by mboskamp** [comment]
Please open a PR
